spring.application.name=task-hotels
server.port=8092

#h2
spring.datasource.url=jdbc:h2:mem:hotels_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=hotel
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

#swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
