spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotels_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect